Feature 003
sw21-tug/Team_15 pull request #19
Opened 2021-04-26 17:09 UTC by chairwinker

ticking timer

2021-04-27 07:36 UTC, haubitzer requested changes

2021-04-27 07:36 UTC, haubitzer commented on app/src/test/java/com/simpletrack/TaskTests.kt
> +import java.util.*
/github/workspace/app/src/test/java/com/simpletrack/TaskTests.kt:8:1: Wildcard import (cannot be auto-corrected)

2021-04-28 06:16 UTC, Chr16t0p approved these changes

2021-04-28 06:19 UTC, haubitzer approved these changes

2021-04-28 06:19 UTC, merged